fix(windows): use utf8 encoding for user log file logger  (semgrep/semgrep-proprietary#3221)
When running the scan subcommand, on success, the message contains
Unicode characters like ✨ which causes an encoding error when writing
to the log file.

```
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 59: character maps to <undefined>
```

This commit explicitly sets the encoding of the file logging handler to
utf8 to fix this issue.

Test plan:

1. Run `semgrep scan -j 1 <file>` on Windows
2. When the file has no errors, `semgrep` prints to the stdout `✨ If
Semgrep missed a finding, please send us feedback to let us know!` and
also logs the same message which causes an encoding error.
3. With this change, the message is logged to the user log file
correctly and the command succeeds

synced from Pro 1bb061b065441cc5338b460987f035ab3a9464ab