osemgrep: centralize error management in CLI.ml
All subcommands should behave the same regarding exn and exit_code
so just simpler to centralize it in CLI.ml instead of
explicitely calling CLI_Common.safe_run in every subcommands

test plan:
```
$ ~/yy/bin/osemgrep --config auto --metrics off .
Error: Cannot create auto config when metrics are off. Please allow metrics or run with a specific config.
```