Use 5s timeout when parsing JS file See the last commit message for more information (#1750)
* * semgrep-core/skip_list.txt: remove LSP stuff

* * semgrep-core/bin/Main.ml: move timeout to Flag_semgrep.ml

* * semgrep-core/parsing/Parse_code.ml: add more logging

* Use 5s timeout for Javascript pfff-based parser

Without the timeout, the semgrep CI was taking 100min instead of
the previous 20min. This was because of some regressions in the the
tree-sitter javascript parser (related to ?.) on huge minified files
that then forced to fallback to the (very slow) pfff-based JS parser.

test plan:
running semgrep-core on a the big
https://github.com/DevSlop/Pixi/blob/master/app/public/api-docs/swagger-ui-bundle.js
file now terminates (but now returns a parse error though)

$ /home/pad/semgrep/_build/default/bin/Main.exe -lang js -e FOO tests/OTHER/PERF/swagger-ui-bundle.js
[0.095  Info       Main.Dune__exe__Main ] loaded log_config.json
[0.095  Info       Main.Dune__exe__Main ] Executed as: /home/pad/semgrep/_build/default/bin/Main.exe -lang js -e FOO tests/OTHER/PERF/swagger-ui-bundle.js
[0.095  Info       Main.Dune__exe__Main ] Version: semgrep-core version: v0.24.0-34-g1138014c-dirty, pfff: 0.42
[0.096  Info       Main.Dune__exe__Main ] processing: tests/OTHER/PERF/swagger-ui-bundle.js
[0.096  Info       Main.Parse_code      ] trying to parse with TreeSitter parser tests/OTHER/PERF/swagger-ui-bundle.js
[0.099  Debug      Main.Parse_code      ] exn (Failure("Line 31, characters 7221-7225:\nnode type: ERROR\nchildren: [\n  number\n  \":\"\n]\nsource code:\n333:\n\nSource code cannot be parsed by tree-sitter.")) with TreeSitter parser
[0.099  Info       Main.Parse_code      ] trying to parse with Pfff parser tests/OTHER/PERF/swagger-ui-bundle.js
[0.099  Info       Main.Parse_code      ] running the pfff JS parser with 5s timeout
[5.098  Debug      Main.Parse_code      ] Timeout, transforming in parse error
[5.098  Debug      Main.Parse_code      ] exn (Parsing.Parse_error) with Pfff parser
[5.099  Debug      Main.Parse_code      ] exn again ((Failure "no parser found for tests/OTHER/PERF/swagger-ui-bundle.js")) but return original exn (Parsing.Parse_error)
[5.099  Debug      Main.Parse_code      ] exn again (Parsing.Parse_error) but return original exn (Failure("Line 31, characters 7221-7225:\nnode type: ERROR\nchildren: [\n  number\n  \":\"\n]\nsource code:\n333:\n\nSource code cannot be parsed by tree-sitter."))
tests/OTHER/PERF/swagger-ui-bundle.js:1:0: Fatal Error: Failure("Line 31, characters 7221-7225:\nnode type: ERROR\nchildren: [\n  number\n  \":\"\n]\nsource code:\n333:\n\nSource code cannot be parsed by tree-sitter.")
Raised at file "parsing/Parse_code.ml", line 80, characters 24-27
Called from file "parsing/Parse_code.ml", line 127, characters 8-797
Called from file "parsing/Parse_code.ml", line 176, characters 12-42
Called from file "bin/Main.ml", line 424, characters 12-78
Called from file "bin/Main.ml", line 411, characters 2-1416
Called from file "bin/Main.ml", line 484, characters 22-45
Called from file "bin/Main.ml", line 692, characters 35-52
Called from file "pfff/h_program-lang/Error_code.ml", line 388, characters 4-8

* * semgrep/tests/public_repos.py: new XFAIL_repo regression