bump click to 8.4.2 (semgrep/semgrep-proprietary#6775)
As requested on OSS.  https://github.com/semgrep/semgrep/issues/11800 .

Naively bumping the version presented two API changes that were
required:

1. TypeError: `CliRunner.__init__()` got an unexpected keyword argument
'mix_stderr' because click 8.2 removed `mix_stderr`.
2. TypeError: `VisibilityStateType.get_metavar()` got an `unexpected
keyword argument 'param'` because click 8.2 changed
`ParamType.get_metavar(self, param)` to `get_metavar(self, param, ctx)`
and now calls it by keyword.

Test plan: CI

(NB: After merging, please let the reporter know that we've done the
version bump!)

synced from Pro 92f0fc38578f0606af12534e4275c49753aa519b