enhancement(validation): Allow `semgrep-internal-metavariable-name` for fast pydantic validation (semgrep/semgrep-proprietary#2189)
## Context

With
[GROW-378](https://linear.app/semgrep/issue/GROW-378/speed-up-rule-parsing-for-cli-scans)
going
[live](https://semgrepinc.slack.com/archives/C03BJ359MRT/p1725473249621939)
in v1.86.0 we now see `pydantic.validate` spans in jaegar
(http://go/jaeger).

<img width="1371" alt="Screenshot 2024-09-05 at 10 19 05 AM"
src="https://github.com/user-attachments/assets/5e0e55ad-3701-4c76-b36e-8d7078da36a2">


Notably, we do see a few validation errors where we fallback to
`jsonschema.validate` which means we can't take advantage of the 20x
speedup. With some quick debugging (error traces are captured!)

```
ValidationError: 867 validation errors for RuleModel
rules.1001.pattern-sources.0.TaintContentPattern.pattern
  Field required [type=missing, input_value={'label': '__SOURCE__', '...r().cleaned_data'}]}]}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
rules.1001.pattern-sources.0.TaintContentPatternsContent.patterns.0.Patterns.patterns.0.PatternEither.pattern-either.34.Patterns.patterns.1
  Unable to extract tag using discriminator pattern_discriminator() [type=union_tag_not_found, input_value={'semgrep-internal-metava...'metavariable': '$CLS'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/union_tag_not_found
```

we see a failure to parse taint rules with usage of
semgrep-internal-metavariable-name .

Paid (aka logged-in / proprietary)
[rules](https://github.com/semgrep/semgrep-rules-proprietary/blob/f4340ba8cb8affda20eed9e631ff096de2d0af60/paid/python/django/db/sqlalchemy-django-relationship.yaml#L180C13-L180C47)
use this for our native framework rules (e.g. django rules). This tag
was recently [introduced into the
schema](https://github.com/semgrep/semgrep-interfaces/commit/1038b234d043849667e1ffc3fbddd9371cc3cfec)
on July 17th, and the pydantic model did not include this field as this
predated the initial model construction back in February.

## Solution

We can quickly update the pydantic model and add a test case to ensure
we successfully validate and do not bail out.

## Test Plan

- [x] Add new test case with example of failing rule that fails without
the fix and succeeds post-fix
- [x] Existing tests pass

synced from Pro 3ef33bc41c9f7cd038a18597c7683fbc69b89b65