fix(sca): fix tuple unpack error (semgrep/semgrep-proprietary#5397)
Test plan:

Luckily, @ajbt200128 made us aware of a failure in the [develop
experiment that pointed us to a tuple unpack
bug](https://semgrepinc.slack.com/archives/C05GV9WR2MB/p1768500509536959).

In https://github.com/semgrep/semgrep-proprietary/pull/5209 we added a
new return value to the `run_scan`'s returned tuple and neglected to
test historical scans so did not catch it.

Tested locally to verify fix.

Before:
```
┌─────────────────────────┐
│ Secrets Historical Scan │
└─────────────────────────┘
⠋ Loading rules...                                                                                                        Scanning 40 files (only git-tracked) with 0 Code rules, 1070 Secrets rules:

  CODE RULES
  Nothing to scan.

  SECRETS RULES

  Language      Rules   Files          Origin      Rules
 ─────────────────────────────        ───────────────────
  <multilang>     749      40          Pro rules    1070
  json              1      11
  ts               69      10
  js               69       5
  python           77       4
  yaml             85       2


  SUPPLY CHAIN RULES

  No rules to run.


  PROGRESS

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
too many values to unpack (expected 14)
Traceback (most recent call last):
  File "/Users/sal/dev/semgrep-proprietary/OSS/cli/src/semgrep/commands/wrapper.py", line 49, in wrapper
    func(*args, **kwargs)
  File "/Users/sal/dev/semgrep-proprietary/OSS/cli/src/semgrep/commands/ci.py", line 837, in ci
    (
ValueError: too many values to unpack (expected 14)
```

After:
```
┌──────────────┐
│ Scan Summary │
└──────────────┘
✅ CI scan completed successfully.
 • Findings: 0 (0 blocking)
 • Rules run: 2140
 • Targets scanned: 40
 • Parsed lines: ~100.0%
 • Scan was limited to files tracked by git
 • For a detailed list of skipped files and lines, run semgrep with the --verbose flag
CI scan completed successfully.
```

PR checklist:
- [x] Documentation is up-to-date
- [ ] An entry was added to
[changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry)
for user-facing changes, and to [CLI
notes](https://golinks.io/cli-notes) for customer support (if needed)
- [x] Change has no security implications (otherwise, ping security
team)
- [x] Change does not log any sensitive information to the INFO,
WARNING, or ERROR log levels (e.g. tokens, analyzed source code)

See [go/saf-pr](http://go/saf-pr) for a guide on our code review process

synced from Pro b9aa2fd5d48220527c41e4825e8eba32e3b4f401