Report uncaught Python exceptions with a stack trace rather than just the exception contents. This allows finding out where the error occurred.
Sample output from `semgrep --test` I'm getting after accidentally
deleting a line:

```
--------------------------------------------------------------------------------
The following config files produced errors:
	python/flask/security/xss/audit/template-unquoted-attribute-var.yaml: Traceback (most recent call last):
  File "/home/martin/semgrep/cli/src/semgrep/test.py", line 304, in invoke_semgrep_multi
    output = semgrep.run_scan.run_scan_and_return_json(config, targets, **kwargs)
  File "/home/martin/semgrep/cli/src/semgrep/run_scan.py", line 771, in run_scan_and_return_json
    ) = run_scan(
  File "/home/martin/semgrep/cli/src/semgrep/run_scan.py", line 573, in run_scan
    ) = run_rules(
  File "/home/martin/semgrep/cli/src/semgrep/run_scan.py", line 217, in run_rules
    ) = core_runner.invoke_semgrep_core(
  File "/home/martin/semgrep/cli/src/semgrep/core_runner.py", line 1042, in invoke_semgrep_core
    ) = self._run_rules_direct_to_semgrep_core(
  File "/home/martin/semgrep/cli/src/semgrep/core_runner.py", line 1016, in _run_rules_direct_to_semgrep_core
    raise e
  File "/home/martin/semgrep/cli/src/semgrep/core_runner.py", line 983, in _run_rules_direct_to_semgrep_core
    return self._run_rules_direct_to_semgrep_core_helper(
  File "/home/martin/semgrep/cli/src/semgrep/core_runner.py", line 923, in _run_rules_direct_to_semgrep_core_helper
    outputs = core_matches_to_rule_matches(rules, core_output)
  File "/home/martin/semgrep/cli/src/semgrep/core_output.py", line 200, in core_matches_to_rule_matches
    rule_match = convert_to_rule_match(match)
  File "/home/martin/semgrep/cli/src/semgrep/core_output.py", line 174, in convert_to_rule_match
    isinstance(rule.product.value, out.Secrets),
NameError: free variable 'rule' referenced before assignment in enclosing scope

Not sending pseudonymous metrics since metrics are configured to OFF and registry usage is False
```