Don't use is_relative_to since we have to support Python 3.8 (semgrep/semgrep-proprietary#1707)
This fixes an error on the main branch introduced by
https://github.com/semgrep/semgrep-proprietary/pull/1654:
```
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'
```

synced from Pro ea52e33a48fe686c3bc9648cf9dd4ff069e2a1fc