Fix 'no such file or directory' for Flask lifecycle harness (semgrep/semgrep-proprietary#1954)
Use `content` instead when the file at the specified location doesn’t
exist. This can happen if the taint trace shows a match in a temporary
fake lifecycle file used for web framework analysis. The issue is
specific to pysemgrep, as for osemgrep, the temporary file isn’t deleted
until osemgrep finishes

An alternative solution could be to allow non-physical source files for
the scan, but this would require larger, fundamental changes. The
current implementation of match reporting heavily relies on physical
files to record the location and code snippet of matches. We would need
to update all relevant code, including `Target` for source files, match
results (including dataflow traces), and the match output definition in
the ATD format, as well as the reporting component in pysemgrep. We may
allocate separate resources in the future to investigate this solution
further.

test plan: manually tested

before:
```
❯ semgrep scan -c tests/interfile/tainting/python/flask_endpoints/deep.yaml tests/interfile/tainting/python/flask_endpoints/app.py --pro
               
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file (only git-tracked) with 1 Code rule:
            
  CODE RULES
  Scanning 1 file.
                    
  SUPPLY CHAIN RULES
                                                       
  💎 Run `semgrep ci` to find dependency
     vulnerabilities and advanced cross-file findings. 
                                                       
          
  PROGRESS
   
Semgrep Pro Engine may be slower and show different results than Semgrep OSS.
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00                                                                                                                        
[Errno 2] No such file or directory: '/var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness85301-240617.py'
Traceback (most recent call last):
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/commands/wrapper.py", line 37, in wrapper
    func(*args, **kwargs)
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/commands/scan.py", line 824, in scan
    output_handler.output(
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/output.py", line 472, in output
    for output_destination, output in self._build_outputs():
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/output.py", line 556, in _build_outputs
    yield self._build_output(output_destination, output_format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/output.py", line 651, in _build_output
    output = formatter.output(  # the rules are used only by the SARIF formatter
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/base.py", line 62, in output
    return self.format(
           ^^^^^^^^^^^^
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/text.py", line 871, in format
    print_text_output(
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/text.py", line 780, in print_text_output
    for line in dataflow_trace_to_lines(
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/text.py", line 384, in dataflow_trace_to_lines
    yield from call_trace_to_lines(
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/text.py", line 316, in call_trace_to_lines
    yield from match_to_lines(
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/formatter/text.py", line 278, in match_to_lines
    lines = get_lines_from_file(path, location.start.line, location.end.line)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heejong/Works/semgrep-proprietary/OSS/cli/src/semgrep/util.py", line 231, in get_lines_from_file
    with path.open(buffering=1, errors="replace") as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/heejong/.pyenv/versions/3.11.9/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness85301-240617.py'
```

after:
```
❯ semgrep scan -c tests/interfile/tainting/python/flask_endpoints/deep.yaml tests/interfile/tainting/python/flask_endpoints/app.py --pro
               
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file (only git-tracked) with 1 Code rule:
            
  CODE RULES
  Scanning 1 file.
                    
  SUPPLY CHAIN RULES
                                                       
  💎 Run `semgrep ci` to find dependency
     vulnerabilities and advanced cross-file findings. 
                                                       
          
  PROGRESS
   
Semgrep Pro Engine may be slower and show different results than Semgrep OSS.
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00                                                                                                                        
                   
                   
┌─────────────────┐
│ 3 Code Findings │
└─────────────────┘
                                                                         
    tests/interfile/tainting/python/flask_endpoints/app.py
    ❯❱ tests.interfile.tainting.python.flask_endpoints.source-to-sink
          Semgrep found a match
                               
           29┆ sink(s)
    
    
          Taint comes from:
    
           26┆ s = source()
    
    
          Taint flows through these intermediate variables:
    
           26┆ s = source()
    
    
                This is how taint reaches the sink:
    
           29┆ sink(s)
    
    
            ⋮┆----------------------------------------
           37┆ sink(g.s)
    
    
          Taint comes from:
    
           /var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness89012-8e215d.py
    
            8┆ run_before_request
    
          Taint flows through these intermediate variables:
    
           30┆ g.s = s
    
           26┆ s = source()
    
          then reaches:
    
           26┆ s = source()
    
    
          Taint flows through these intermediate variables:
    
           30┆ g.s = s
    
    
                This is how taint reaches the sink:
    
           /var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness89012-8e215d.py
    
            9┆ func1
    
          Taint flows through these intermediate variables:
    
           38┆ return g.s
    
          then reaches:
    
           37┆ sink(g.s)
    
    
            ⋮┆----------------------------------------
           52┆ sink(g.s)
    
    
          Taint comes from:
    
           /var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness89012-8e215d.py
    
            5┆ run_before_request
    
          Taint flows through these intermediate variables:
    
           30┆ g.s = s
    
           26┆ s = source()
    
          then reaches:
    
           26┆ s = source()
    
    
          Taint flows through these intermediate variables:
    
           30┆ g.s = s
    
    
                This is how taint reaches the sink:
    
           /var/folders/pm/c1v7kj9s70jf17k8_vjzgj0m0000gp/T/flask_lifecycle_harness89012-8e215d.py
    
            6┆ func3
    
          Taint flows through these intermediate variables:
    
           53┆ return g.s
    
          then reaches:
    
           52┆ sink(g.s)
    

                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘
Some files were skipped or only partially analyzed.
  Scan skipped: 1 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1 rule on 1 file: 3 findings.
```

synced from Pro d27f072599f84764ebc076dcb1c70a17b1d05491