bump flake8 version for python 3.14 (semgrep/semgrep-proprietary#5877)
After upgrading to Python 3.14, pre-commit started failing with an
`AttributeError: module 'ast' has no attribute 'Num'` exception deep
inside flake8. The cause is such fields in `ast` got deprecated ages ago
and are now finally
[gone](https://docs.python.org/dev/whatsnew/3.14.html#id9) as of that
python release.

The pre-commit config file has us pinned to an ancient version of flake8
(and indeed all our pre-commit versions), with a scary warning
indicating that these versions should not be bumped. This patch ignores
that comment block and bumps the version of flake8 to the [earliest
version](https://flake8.pycqa.org/en/latest/release-notes/7.3.0.html)
supported by python 3.14, and bumps the bugbear dependency to latest as
of this commit date.

Additionally, bumping the major version of flake8 revealed some more
findings: many are valid (it appears some OCaml person wrote `()` rather
than `pass`) but many are spurious (we are aware of the memory cost of
lru_caches, thank you very much, even if they _are_ attached to instance
methods in some cases). The former is fixed in this PR and the latter
are skipped via ` # noqa` annotations or globally in the flake8 config
file.

As followup work, we should revisit the aforementioned scary comment
block - it alludes to the eventual removal of the Python CLI, which of
course was and is not going to happen. @yosefAlsuhaibani has mentioned
that perhaps autoflake subsumes a lot of flake8's functionality, so
maybe we can just pull one or the other out as followup work, too.

Test plan: Ensure CI passes with the stock Python interpreter installed
on the runners.

synced from Pro ae959a6e3c3bf530fd8c811aaa84718ba3ed145b