Report semgrep-core's message upon a parse error
Sometimes it's not actually a parse error even though we report it as
such, so it is useful to know what semgrep-core actually reported.

Related-to: #3547

test plan:
    $ cat bad.py
    def foo():
      return 1
    }
    $ semgrep -v -l py -e '$X' bad.py
    ...
    Could not parse bad.py as python

    semgrep-core message:

    	Fatal Error: (Failure "Lexer_python.top_mode: empty stack")

    #^ now we understand better what is going on