Fix bug caused by the new 'missed: <int>' field in rule files. (#9140)
For now, extra top-level fields in rule files are tolerated.

Update: only a `rules` field is now allowed and a nice error message is
produced otherwise.

Test plan:
```
$ cat > foo.yaml
rules: []
extra: 42
$ semgrep --experimental -c foo.yaml
Error: exception invalid YAML, foo.yaml:3:0: duplicate key "duplicate key 'rules' in dictionary"
...
Error: fatal error
Exiting with error status 2: osemgrep --experimental -c foo.yaml
```

I don't know if we have a convenient way of checking for stdout/stderr
output in OCaml tests, that's why I didn't add a test for this.