Fix log timestamps shown before calls to 'setup_logging' (#9854)
test plan:
Before:
```
$ semgrep show
[1709096337.46][ERROR]: 'semgrep show' expects a subcommand. Try 'semgrep show --help'.
Error: fatal error
Exiting with error status 2: osemgrep show
```
After:
```
$ semgrep show
[00.07][ERROR]: 'semgrep show' expects a subcommand. Try 'semgrep show --help'.
Error: fatal error
Exiting with error status 2: osemgrep show
```

I also removed the line that resets the timeline in `setup_logging`
because we don't want logs to appear to travel backwards in time. The
origin of times is now set to whenever the `Logs_` module is
initialized.

---------

Co-authored-by: Cooper Pierce <cooper@semgrep.com>