Show a decent error message on 'semgrep show' (#9852)
test plan:
```
$ semgrep show
[1709096337.46][ERROR]: 'semgrep show' expects a subcommand. Try 'semgrep show --help'.
Error: fatal error
Exiting with error status 2: osemgrep show
```