WIP: Ruby tree-sitter integration (#1127)
* Require a more recent version of dune, used to compile C and C++ files
from tree-sitter.

* Add submodule ocaml-tree-sitter-lang

* Use latest Ruby boilerplate

* Use latest ocaml-tree-sitter-lang

* Bento-ignore new submodule ocaml-tree-sitter-lang

* Add trailing slash to bento-ignored directory

* Add setup for ocaml-tree-sitter

* Use latest ocaml-tree-sitter

* Fixes for ocaml-tree-sitter setup

* Add missing step to workflow

* Connecting to add_lang branch in pfff adding Ruby and Typescript in Lang.ml

Test plan:
make
make test

* * semgrep-core/bin/Main.ml: new -parse_ruby action testing tree-sitter parsers

* * semgrep-core/bin/Main.ml: run parser in its own process, to avoid
segfaults

test plan:
Main.exe -parse_ruby ~/work/lang-ruby
which is a big corpus of ruby projects (rails, gitlab) does not
segfault anymore and return pretty good parsing stats
(97% on rails). Far better than the Ruby parser in pfff which
can deal with only 15% of modern rails code.

* Factorize code in Parse_code.ml

This will help the gradual transition to tree-sitter parsers.
We can now in Parse_code.ml call not only pfff parser but also tree-sitter
parsers

Test plan:
make test

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: Skeleton code

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: just copy boilerplate

Now needs to fill it ...

Test plan:
pad@yrax:~/semgrep$ yy -dump_ast tests/ruby/foo.rb
+ /home/pad/github/semgrep/semgrep-core/_build/default/bin/Main.exe -dump_ast tests/ruby/foo.rb
(((Stmts_rep1_choice_stmt_term_opt_stmt
   (((Stmt_term
      ((Stmt_exp
        (Exp_cmd_call
         (Cmd_call_choice_var_cmd_arg_list
          ((Var (Id puts))
           (Cmd_arg_list_arg_rep_COMMA_arg
            ((Arg_arg
              (Arg_prim
               (Prim_str ("\"" (((Str_content "Hello World"))) "\""))))
             ()))))))
       (Term_line_brk ""))))
    ())))
 ())
Fatal error: exception (Failure "not implemented")
Raised at file "stdlib.ml", line 29, characters 22-33
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 1142, characters 20-30
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 216, characters 23-35
Called from file "list.ml", line 92, characters 20-23
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 213, characters 8-258
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 1660, characters 16-28
Called from file "parsing/Parse_code.ml", line 29, characters 16-49
Called from file "parsing/Parse_code.ml", line 38, characters 12-42
Called from file "bin/Main.ml", line 773, characters 12-48
Called from file "Common.ml", line 1294, characters 12-16
Re-raised at file "Common.ml", line 1292, characters 8-302
Called from file "Common.ml", line 1262, characters 45-49
Called from file "Common.ml", line 82, characters 14-18
Re-raised at file "Common.ml", line 87, characters 10-11
Called from file "Common.ml", line 1259, characters 6-10
Called from file "bin/Main.ml", line 1134, characters 2-55

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: handling basic
puts "Hello World"

* * semgrep-core/tests/ruby/foo.rb: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * pfff: using latest from add_lang with ast_ruby modifications

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress before I stop
for today

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: misc

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * pfff: use latest add_lang

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: progress

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: no more Todo! v0!

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: use latest pfff

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs new ast_ruby.ml

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: use Char|Complex|Rational

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: use new variable type

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: more

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: indent

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs using latest ast_ruby.ml

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs using latest, DotAccess

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* Update ocaml-tree-sitter

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs recscue_clause, and no
more 'fk'!

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs Block and bracket

* * semgrep-core/parsing/Parse_ruby_tree_sitter.ml: CEs option2 removal

* * pfff: use latest!

* Fix incorrect build commands for ocaml-tree-sitter's runtime.

* Fix dependency setup

* Use latest ocaml-tree-sitter

* Run new configure step in ocaml-tree-sitter install

* Use alpine instead of debian+musl

* Update ocaml-tree-sitter

* Show commit info

* Fix non-exhaustive pattern match

* Update submodule pfff

* Switch to alpine for all ocaml builds in github actions.

* Try to set up python for alpine

* Force static linking on alpine

* Try using python 3.8

* Split benchmark.yml into two alpine/ocaml and debian/python

* Fix config

* Add missing copy to export semgrep-core

* Factor out the semgrep-core build

* Add optional 'git clone' for convenience

* Update pfff

* Update pfff

* Split python-dependent tests from semgrep-core build

* Restore the bizarre 'opam env --root /home/opam/.opam --set-root'

* Update ocaml-tree-sitter

* Make ubuntu release reuse the semgrep-core binary.

* Add missing checkout step

* Fix this and that

* * pfff: use latest add_lang, merged

* use latest pfff add_lang branch and CEs

* Fix dockerfile

* Add a root makefile that supports 'make clean'

* Add cleanup step before starting the build.

* * pfff: use latest

* * semgrep-core/bin/Main.ml: Fix possible regression introducing when merging
develop in tree-sitter.

Probably during some past merge, we used Parse_generic.parse_with_lang
which does not resolve name instead of the correct (but easy
to mispell) Parse_code.parse_with_lang.
This meant many tests were failing because we were not resolving names
anymore.

Test plan:
make test in semgrep now work

* * semgrep-core/tests/python/misc_faketok3.py: fix regression

* * Dockerfile: shutup the warning about sudo

There is probably a better way to fix this ... but right now
I really want to merge the tree-sitter branch in develop so
this will have to wait.
@brendon or @matt for help fixing that.

Co-authored-by: pad <yoann.padioleau@gmail.com>
Co-authored-by: Martin Jambon <Martin Jambon>