Add opentelemetry dependency to CLI (semgrep/semgrep-proprietary#1818)
First step towards adding tracing to the CLI. This PR contains fixes for
CI to resolve build/test failures from adding the new dependencies.
Seems like adding the new dependencies busted some caches and the logic
to regenerate hasn't been exercised in quite a while.

Error #1:
```
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: ERROR: .[experiments]; python_version >= '3.8' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
ERROR: Couldn't install package: semgrep
 Package installation failed...
```

Looks like extras was added as part of this PR:
https://github.com/semgrep/semgrep/pull/6048/files and partially removed
in this one: https://github.com/semgrep/semgrep/pull/9621/files. I fully
removed in this PR.

Error #2:
```
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: ERROR: .; python_version >= '3.8' is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
ERROR: Couldn't install package: semgrep
 Package installation failed...
```
I noticed I couldn't reproduce this issue locally with `pipenv` version
`2024.0.1` and that CI was pinned to a version from 2022. I upgraded
pipenv to resolve.

Error #3:
```
ERROR: Could not find a version that satisfies the requirement pipenv==2024.0.1
```
The benchmarks checks pinned python 3.7 which we no longer support and
this is not compatible with the newer version of pipenv. I updated
benchmarks to use Python 3.8 which is compatible.

Error #4 (benchmarks):
```
pipenv.patched.pip._internal.exceptions.InstallationError: Invalid requirement: '-y'
```

The `run-pro-benchmarks.sh` script uses different syntax in different
places to uninstall semgrep:
`pipenv uninstall semgrep`
`pipenv uninstall -y semgrep`

There's only one instance in the file of the `-y` flavor, I removed it
since the flavor without it seems to work fine.

Success!

The last remaining failing check build-os-x86 doesn't seem to be related
to this change as it's also appearing on many other open PRs with the
same error message and discussion in Slack indicates yet another caching
issue.

synced from Pro b219cc45354c2913ba9d76793da86fd69d3e0153