fix: check if tool exists before deregistering tool (semgrep/semgrep-proprietary#6157)
We don't check if the tool is already deregistered/ if the tool exists
when we remove the tool, so if a user tries to deregister a tool using
the env vars and the tool has already been deactivated for other
reasons, a key error is thrown. This bug has been reported in the [OSS
repo](https://github.com/semgrep/semgrep/issues/11646#issuecomment-4290272420).

This PR adds checks before deregistering a tool so we won't try to
deregister a tool that has already been deregistered.

Test plan: Tried deregistering a the remote scan tool with an env var in
local mode
Before:
```
2026-04-29 23:38:57.518 [error]   File "/Users/katrinaliu/.local/share/uv/tools/semgrep/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katrinaliu/.local/share/uv/tools/semgrep/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/katrinaliu/dev/semgrep-proprietary/OSS/cli/src/semgrep/commands/mcp.py", line 193, in semgrep_mcp
    deregister_tools(mcp, transport)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/katrinaliu/dev/semgrep-proprietary/OSS/cli/src/semgrep/mcp/server.py", line 1382, in deregister_tools
    del mcp._tool_manager._tools["semgrep_scan_remote"]
        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'semgrep_scan_remote'
 undefined
```
After:
No error

synced from Pro 4b10b90c2bc2e535dfa3558c5c9f4062dfc5bfb7