* semgrep-core/parsing/Parse_ruby_tree_sitter.ml: just copy boilerplate
Now needs to fill it ...

Test plan:
pad@yrax:~/semgrep$ yy -dump_ast tests/ruby/foo.rb
+ /home/pad/github/semgrep/semgrep-core/_build/default/bin/Main.exe -dump_ast tests/ruby/foo.rb
(((Stmts_rep1_choice_stmt_term_opt_stmt
   (((Stmt_term
      ((Stmt_exp
        (Exp_cmd_call
         (Cmd_call_choice_var_cmd_arg_list
          ((Var (Id puts))
           (Cmd_arg_list_arg_rep_COMMA_arg
            ((Arg_arg
              (Arg_prim
               (Prim_str ("\"" (((Str_content "Hello World"))) "\""))))
             ()))))))
       (Term_line_brk ""))))
    ())))
 ())
Fatal error: exception (Failure "not implemented")
Raised at file "stdlib.ml", line 29, characters 22-33
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 1142, characters 20-30
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 216, characters 23-35
Called from file "list.ml", line 92, characters 20-23
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 213, characters 8-258
Called from file "parsing/Parse_ruby_tree_sitter.ml", line 1660, characters 16-28
Called from file "parsing/Parse_code.ml", line 29, characters 16-49
Called from file "parsing/Parse_code.ml", line 38, characters 12-42
Called from file "bin/Main.ml", line 773, characters 12-48
Called from file "Common.ml", line 1294, characters 12-16
Re-raised at file "Common.ml", line 1292, characters 8-302
Called from file "Common.ml", line 1262, characters 45-49
Called from file "Common.ml", line 82, characters 14-18
Re-raised at file "Common.ml", line 87, characters 10-11
Called from file "Common.ml", line 1259, characters 6-10
Called from file "bin/Main.ml", line 1134, characters 2-55