Docker: update to returntocorp/ocaml:alpine-2023-03-03
This currently fails to build ... I get weird errors early about
distlib:
```
(1/1) Installing python3-dev (3.8.10-r0)
Executing busybox-1.31.1-r16.trigger
OK: 705 MiB in 128 packages
pip install --no-cache-dir pipenv
Requirement already satisfied: pipenv in /usr/lib/python3.8/site-packages (2023.2.18)
Requirement already satisfied: certifi in /usr/lib/python3.8/site-packages (from pipenv) (2020.4.5.1)
Collecting setuptools>=67.0.0
  Downloading setuptools-67.6.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/lib/python3.8/site-packages (from pipenv) (0.5.7)
Requirement already satisfied: virtualenv>=20.17.1 in /usr/lib/python3.8/site-packages (from pipenv) (20.20.0)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/lib/python3.8/site-packages (from virtualenv>=20.17.1->pipenv) (3.9.0)
Requirement already satisfied: platformdirs<4,>=2.4 in /usr/lib/python3.8/site-packages (from virtualenv>=20.17.1->pipenv) (3.1.0)
Installing collected packages: setuptools, distlib
  Attempting uninstall: setuptools
    Found existing installation: setuptools 47.0.0
    Uninstalling setuptools-47.0.0:
      Successfully uninstalled setuptools-47.0.0
  Attempting uninstall: distlib
    Found existing installation: distlib 0.3.0
ERROR: Cannot uninstall 'distlib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
make: *** [Makefile:233: install-deps-ALPINE-for-semgrep-core] Error 1
The command '/bin/sh -c make install-deps-ALPINE-for-semgrep-core &&    make install-deps-for-semgrep-core' returned a non-zero code: 2
make: *** [Makefile:105: build-docker] Error 2
```

test plan:
make build-docker