feat(parallelism): yielding combinator (semgrep/semgrep-proprietary#4515)
Recall that we use Eio's cooperative scheduler to handle timeouts for multicore scans.  This means that periodically we, as a CPU-bound Eio fiber, need to "check in" with the scheduler to see if we've blown our timeout deadline.

In the past, we've done so "imperatively" with the `Domains.maybe_yield` primitive.  There's nothing wrong with this, per se, but an idiom that we seem to be converging on is "perform some operation, and at the end, check in with Eio".  To this end, this patch implements the `yielding` combinator, which wraps a function such that when it is called, the supplied function is called followed by `Domains.maybe_yield ()`.

This patch still leaves that explicit yield point visible to the code base; we might still want to explicitly yield in the middle of a long function, for instance.

As an initial use-case, this patch builds atop #4514, which measures a good example of a pathological "blow-past-our-deadline" scenario: what should have been terminated after five seconds takes us now ~30.

```
[31.61][ERROR](semgrep.engine): timeout for rule javascript.nestjs.file.sharp-nestjs.sharp-nestjs on file swagger-ui-es-bundle-core.js
[31.61][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[32.48][DEBUG](default)(semgrep.engine): found 1670 matches
[32.48][DEBUG](default)(semgrep.engine): evaluating the formula
[32.48][DEBUG](default)(semgrep.engine): found 0 final ranges
[32.48][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[34.61][DEBUG](default)(semgrep.engine): found 0 matches
[34.61][DEBUG](default)(semgrep.engine): evaluating the formula
[34.61][DEBUG](default)(semgrep.engine): found 0 final ranges
[34.61][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[34.69][DEBUG](default)(semgrep.engine): found 0 matches
[34.69][DEBUG](default)(semgrep.engine): evaluating the formula
[34.69][DEBUG](default)(semgrep.engine): found 0 final ranges
[34.69][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[34.77][DEBUG](default)(semgrep.engine): found 0 matches
[34.77][DEBUG](default)(semgrep.engine): evaluating the formula
[34.77][DEBUG](default)(semgrep.engine): found 0 final ranges
[34.77][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[35.10][DEBUG](default)(semgrep.engine): found 8852 matches
[35.10][DEBUG](default)(semgrep.engine): evaluating the formula
[60.35][DEBUG](default)(semgrep.engine): found 0 final ranges
[60.35][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[60.35][ERROR]: exception during Match_tainting_mode.check_rules.(fun):
input:
target: swagger-ui-es-bundle-core.js
ruleid: javascript.koa.file.sharp-koa.sharp-koa
exception: Cancelled: Eio__core__Fiber.Not_first
backtrace:

[60.35][WARNING]: "Match_rules.timeout_function" timeout at 5 s (we abort)
```

After this patch, we have introduced enough sync points that we now time out after ~5 seconds, as we expect.

```
[10.66][ERROR](semgrep.engine): timeout for rule javascript.nestjs.file.sharp-nestjs.sharp-nestjs on file swagger-ui-es-bundle-core.js
[10.66][DEBUG](default)(semgrep.engine): formula for javascript.koa.file.sharp-koa.sharp-koa has as_metavariable: false
[15.66][ERROR](commons): protect: Fun.Finally_raised: Cancelled: Eio__core__Fiber.Not_first

[15.66][ERROR]: exception during Match_tainting_mode.check_rules.(fun):
input:
target: swagger-ui-es-bundle-core.js
ruleid: javascript.koa.file.sharp-koa.sharp-koa
exception: Cancelled: Eio__core__Fiber.Not_first
backtrace:

[15.66][WARNING]: "Match_rules.timeout_function" timeout at 5 s (we abort)
```

Test plan: apart from minified JS local test, CI (since there is an existing test there for timeouts in the matching combinators)

synced from Pro 238abf0224f6c997dd5d80fe7f618e2d359726bb